version: "3"

networks:
  faasm:

services:
  redis:
    image: redis
    ports:
      - "6378:6379"
    networks:
      - faasm

  worker:
    image: shillaker/faasm-worker:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FUNC_ROOT=/usr/share/faasm
      - CGROUP_MODE=on
      - NETNS_MODE=one
    volumes:
      - ./wasm:/usr/share/faasm/wasm
    networks:
      - faasm
    privileged: true

  edge:
    image: shillaker/faasm-edge:latest
    ports:
      - "8001:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FUNC_ROOT=/usr/share/faasm
    volumes:
      - /usr/share/faasm:/usr/share/faasm
    depends_on:
      - redis
    networks:
      - faasm
