version: "3"

networks:
  faasm:

services:
  redis:
    image: redis
    ports:
      - "6378:6379"
    networks:
      - faasm

  worker:
    image: shillaker/faasm-core:latest
    command: "/faasm/code/build/bin/worker"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FUNC_ROOT=/usr/share/faasm
    volumes:
      - /usr/share/faasm:/usr/share/faasm
      - /sys/fs/cgroup:/sys/fs/cgroup  # For cgroup management
      - /var/run/netns:/var/run/netns
    networks:
      - faasm

  edge:
    image: shillaker/faasm-core:latest
    command: "/faasm/code/build/bin/edge"
    ports:
      - "8001:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FUNC_ROOT=/usr/share/faasm
    volumes:
      - /usr/share/faasm:/usr/share/faasm
    depends_on:
      - redis
    networks:
      - faasm
