version: '2'

services:
  redis:
    image: redis

  edge:
    build: edge.dockerfile
    environment:
      - REDIS_HOST = "redis"
    volumes:
      - /usr/local/code/faasm/:/faasm/code/
    ports:
      - "8002:8002"
    depends_on:
      - redis

  worker:
    build: worker.dockerfile
    environment:
      - REDIS_HOST = "redis"
    volumes:
      - /usr/local/code/faasm/:/faasm/code/
    ports:
      - "8001:8001"
    depends_on:
      - edge


