version: "3"
services:
  redis:
    image: redis
    ports:
      - "6378:6379"

  worker:
    build:
      context: .
      dockerfile: worker.dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - FUNC_ROOT=/usr/share/faasm
    volumes:
      - ./wasm:/usr/share/faasm

  edge:
    build:
      context: .
      dockerfile: edge.dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - FUNC_ROOT=/usr/share/faasm
    volumes:
      - ./wasm:/usr/share/faasm
    depends_on:
      - redis
