---

- name: "Install packages"
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "bridge-utils"
    - "iproute2"

- name: "Enable IP forwarding on host"
  become: yes
  shell: "echo 1 > /proc/sys/net/ipv4/ip_forward"

- name: "Ensure at least one public DNS server configured (for local testing of namespaces)"
  become: yes
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver.*8.8.8.8"
    line: "nameserver   8.8.8.8"

# Repeat namespace creation as many times as necessary
# Note, we index cgroups from 1
- name: "Set up {{ ns_count }} namespaces"
  include_tasks: namespace.yml
  loop: "{{ range(1, ns_count + 1) | list }}"
  loop_control:
    loop_var: ns_idx
