---

- set_fact:
    cg_name: "faasm{{ cg_idx }}"

- name: "Create group"
  become: yes
  shell: "cgcreate -t {{ ansible_user }}:{{ ansible_user }} -a {{ ansible_user }}:{{ ansible_user }} -g {{ controllers }}:/faasm/{{ cg_name }}"

# ----------------------------
# net_cls group
# ----------------------------

# Assign a class ID to the cgroup. Note, class IDs need to be expressed in a 64-bit-wide hex format (can leave
# off leading zeroes), so 3:8 is 10008 and 3:11 is 1000b
# See https://www.kernel.org/doc/Documentation/cgroup-v1/net_cls.txt
- name: "Format class ID to write to file"
  shell: 'printf "0x3%04x" {{ cg_idx }}'
  register: "cls_handle"

- name: "Set class ID {{ cls_handle }} on cgroup {{ cg_name }}"
  become: yes
  shell: "echo {{ cls_handle.stdout }} > /sys/fs/cgroup/net_cls/faasm/{{ cg_name }}/net_cls.classid"

# ----------------------------
# Traffic shaping
# ----------------------------

- set_fact:
    rate_limit: "1024kbps"
    rate_ceil: "2048kbps"
    buffer: "32kbit"
    max_latency: "100ms"

- name: "Create a tc class to handle these packets"
  become: yes
  shell: "tc class add dev eth0 parent 3: classid 3:{{ cg_idx }} htb rate {{ rate_limit }} ceil {{ rate_ceil }}"

- name: "Create a tc filter to assign packets to this group"
  become: yes
  shell: "tc filter add dev eth0 parent 3: protocol ip prio 10 handle 3:{{ cg_idx }} cgroup"
