apiVersion: v1
kind: Pod
metadata:
  name: edge
  namespace: faasm
  labels:
    app: faasm
    role: edge
spec:
  containers:
    - name: edge
      image: shillaker/faasm-edge:0.0.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      env:
        - name: REDIS_HOST
          value: redis
      volumeMounts:
        - mountPath: "/usr/share/faasm"
          name: func-vol
  volumes:
  - name: func-vol
    persistentVolumeClaim:
      claimName: func-storage-claim