apiVersion: v1
kind: Pod
metadata:
  name: edge
  namespace: faasm
  labels:
    app: faasm
spec:
  containers:
    - name: edge
      image: shillaker/faasm-edge:0.0.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      env:
        - name: REDIS_HOST
          value: redis