apiVersion: v1
kind: Pod
metadata:
  name: edge
  namespace: faasm
  labels:
    app: faasm
    role: edge
spec:
  containers:
    - name: edge
      image: shillaker/faasm-edge
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: FUNC_ROOT
          value: /usr/share/faasm  
      volumeMounts:
        - mountPath: "/usr/share/faasm"
          name: func-vol
  volumes:
  - name: func-vol
    persistentVolumeClaim:
      claimName: func-storage-claim
