apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: faasm
  labels:
    app: faasm
spec:
  replicas: 4
  selector:
    matchLabels:
      app: faasm
      role: edge
  template:
    metadata:
      labels:
        app: faasm
        role: edge
    spec:
      containers:
      - name: edge
        image: faasm/edge
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: FUNC_ROOT
          value: /usr/share/faasm
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - mountPath: "/usr/share/faasm"
          name: func-vol
      volumes:
      - name: func-vol
        persistentVolumeClaim:
          claimName: func-storage-claim
