apiVersion: v1
kind: PersistentVolume
metadata:
  name: func-storage
  namespace: faasm
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /usr/share/faasm
    server: 192.168.0.13

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: func-storage-claim
  namespace: faasm
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
