apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: faasm
  labels:
    app: faasm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faasm
      role: worker
  template:
    metadata:
      labels:
        app: faasm
        role: worker
    spec:
      containers:
        - name: worker
          image: shillaker/faasm-worker:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: REDIS_HOST
              value: redis
            - name: PROJ_ROOT
              value: /faasm/code