apiVersion: v1
kind: Pod
metadata:
  name: worker
  namespace: faasm
  labels:
    app: faasm
spec:
  containers:
    - name: worker
      image: shillaker/faasm-worker:0.0.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8001
      env:
        - name: REDIS_HOST
          value: redis
        - name: PROJ_ROOT
          value: /faasm/code