apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: faasm
  labels:
    app: faasm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faasm
      role: worker
  template:
    metadata:
      labels:
        app: faasm
        role: worker
    spec:
      containers:
        - name: worker
          image: shillaker/faasm-core:latest
          imagePullPolicy: IfNotPresent
          command: "/faasm/code/build/bin/worker"
          ports:
            - containerPort: 8001
          env:
            - name: REDIS_HOST
              value: redis
            - name: FUNC_ROOT
              value: /usr/share/faasm
          volumeMounts:
            - mountPath: "/usr/share/faasm"
              name: func-vol
      volumes:
      - name: func-vol
        persistentVolumeClaim:
          claimName: func-storage-claim