---

- name: "Clone wavm"
  git:
    repo: "https://github.com/Shillaker/WAVM"
    dest: "/usr/local/code/WAVM"
    update: yes

- name: "Set up remote"
  shell: "git remote add upstream https://github.com/AndrewScheidecker/WAVM"
  args:
    chdir: "/usr/local/code/WAVM"
  ignore_errors: yes

- name: "Create build directory"
  file:
    path: "/usr/local/code/WAVM/build"
    state: directory
    mode: 0755

- name: "Build wavm"
  shell: "{{ item }}"
  args:
      chdir: "/usr/local/code/WAVM/build"
  with_items:
    - "cmake -DCMAKE_BUILD_TYPE=Release .."
    - "cmake --build . --target all"
