---

# See the net_cls cgroup docs for set-up info: https://www.kernel.org/doc/Documentation/cgroup-v1/net_cls.txt

- name: "Set handle for network class of cgroup"
  become: yes
  shell: "echo 0x100001 >  /sys/fs/cgroup/net_cls/faasm/net_cls.classid"

- name: "Add qdisc"
  become: yes
  shell: "tc qdisc add dev eth0 root handle 10: htb"

- name: "Add a traffic class"
  become: yes
  shell: "tc class add dev eth0 parent 10: classid 10:1 htb rate 40mbit"

- name: "Add a filter"
  become: yes
  shell: "tc filter add dev eth0 parent 10: protocol ip prio 10 handle 1: cgroup"

