---

- name: "Create cgconfig directory"
  become: yes
  file:
    path: "/etc/cgconfig.d/"
    state: directory

- name: "Get current user ID"
  shell: "id -u"
  register: "uid"

- debug:
    var: uid

- name: "Put cgroup config files in place"
  become: yes
  template:
    src: cgconfig-faasm.j2
    dest: "/etc/cgconfig.d/faasm.conf"

- name: "Set up cgroups"
  become: yes
  shell: "cgconfigparser -a {{ ansible_user }}:{{ ansible_user }} -L /etc/cgconfig.d"
