---

- name: "Ensure code is updated"
  git:
    repo: "git@gitlab.ibr.cs.tu-bs.de:shillake/faasm.git"
    dest: "/home/{{ ansible_user }}/faasm"
    clone: yes
    update: yes

- name: "Deploy to kubernetes"
  shell: "{{ item }}"
  args:
    chdir: "/home/{{ ansible_user }}/faasm"
  with_items:
    - "kubectl apply -f k8s/namespace.yml"
    - "kubectl apply -f k8s"
