---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Clone binaryen and wabt"
      git:
        repo: "https://github.com/Webassembly/{{ item }}"
        dest: "/usr/local/code/{{ item }}"
      with_items:
        - binaryen
        - wabt

    - name: "Build binaryen"
      shell: "{{ item }}"
      args:
        chdir: "/usr/local/code/binaryen"
      with_items:
        - "cmake ."
        - "make"

    - name: "Build wabt"
      shell: "{{ item }}"
      args:
        chdir: "/usr/local/code/wabt"
      with_items:
        - "make"

