---

- hosts: localhost
  gather_facts: yes
  tasks:
    - set_fact:
        controllers: "cpu"

    - name: "System deps"
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
      - cgroup-bin
      - cgroup-tools

    - name: "Delete top-level cgroup if exists"
      become: yes
      shell: "cgdelete {{ item }}:/faasm | true"
      with_items:
      - "cpu"

    - name: "Create top-level cgroup"
      become: yes
      shell: "cgcreate -t {{ ansible_user }}:{{ ansible_user }} -a {{ ansible_user }}:{{ ansible_user }} -g {{ controllers }}:/faasm"

