---

- hosts: localhost
  gather_facts: no
  tasks:
    # System deps
    - name: "Install deps with apt"
      become: yes
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "libz-dev"
        - "libboost-dev"
        - "libcpprest-dev"
        - "libhiredis-dev"
        - "libcgroup-dev"
        - "libcurl4-openssl-dev"
        - "cgroup-tools"
        - "cgroup-bin"
        - "iproute2"
