---

- name: "Ensure directory exists"
  become: yes
  file:
    path: "/usr/local/faasm/net"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
    recurse: yes

- name: "Put network-related files in place"
  copy:
    src: "{{ item }}"
    dest: "/usr/local/faasm/net/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items:
    - "hosts"
    - "resolv.conf"